# Generated by Django 5.2.4 on 2025-08-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper', models.BooleanField(default=False)),
                ('lower', models.BooleanField(default=True)),
                ('numbers', models.BooleanField(default=True)),
            ],
        ),
    ]
